### ISSUE TITLE
toValue error dialog because of getValue() in ReadableNativeMap.java after dragging list item on other item in android

### ISSUE THREAD

**Issue by raufshk** [thomasrovayaz/react-native-draggable-dynamic-flatlist#7] opened 2019-12-05 06:42 UTC
In android after dragging one list item to other app crashesh with toValue error dialog because of getValue() in ReadableNativeMap.java error.
![Screenshot_2019-12-02-18-30-51-471_com applications gymshim gym](https://user-images.githubusercontent.com/38748010/70210376-7a061000-1758-11ea-92d4-e48f4d84919b.jpg)

**Comment by raufshk** [comment] 2019-12-05 06:46
<DraggableFlatList

          data={props.data}
          extraData={props}
          renderItem={getListItem}
          keyExtractor={(item, index) => `draggable-item-${index}`}
          scrollPercent={10}
          onMoveEnd={({ data }) => props.moveEnd(data)}

        />

React Native : 0.55.4
"react-native-draggable-dynamic-flatlist": "1.0.2"

Trying to solve the issue but no success any suggestions are welcome

**Comment by thomasrovayaz** [comment] 2020-04-11 16:37
Duplicate of https://github.com/facebook/react-native/issues/23268

**Closed as completed by thomasrovayaz** 2020-04-11 16:37 UTC
